# Generated by Django 3.0.5 on 2020-04-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sedes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
