# Generated by Django 3.0.5 on 2020-04-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sedes', '0002_auto_20200416_0049'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rol',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=300),
        ),
    ]
