# Generated by Django 3.0.5 on 2020-04-14 11:08

from django.db import migrations, models
import django.db.models.deletion
import sedes.models


class Migration(migrations.Migration):

    dependencies = [
        ('sedes', '0002_auto_20200414_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', sedes.models.NameField(max_length=25, unique=True, verbose_name='Nombre de categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('dpi', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('nit', models.CharField(max_length=15)),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('codigo_barras', models.CharField(max_length=50, verbose_name='Codigo de Barras')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=500)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('categorias', models.ManyToManyField(to='sedes.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(choices=[('VE', 'Vendedor'), ('BO', 'Bodeguero'), ('RE', 'Repartidor'), ('EN', 'Encargado')], default='VE', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='sede',
            name='numero_bodegas',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_facturacion', models.DateField(verbose_name='Fecha de facturacion')),
                ('tipo', models.CharField(choices=[('D', 'A domicilio'), ('L', 'Local')], default='L', max_length=1)),
                ('fecha_entrega', models.DateField(auto_now=True, verbose_name='Fecha de entrega')),
                ('entregada', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedes.Cliente')),
                ('repartidor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repartidor', to='sedes.Usuario')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendedor', to='sedes.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedes.Producto')),
                ('venta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sedes.Venta')),
            ],
        ),
        migrations.CreateModel(
            name='LogActualizacionInventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_nueva', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad_vieja', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion', models.CharField(max_length=500)),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de cambio')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sedes.Producto')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sedes.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recargo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('venta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sedes.Venta')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='sedes',
            field=models.ManyToManyField(to='sedes.Sede'),
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=500)),
                ('estado', models.CharField(choices=[('A', 'Activa'), ('I', 'Inactiva')], default='A', max_length=1)),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedes.Usuario')),
            ],
        ),
    ]
