# Generated by Django 3.0.5 on 2020-04-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sedes', '0003_auto_20200416_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='alias',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
