# Generated by Django 3.0.5 on 2020-04-27 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sedes', '0004_auto_20200416_2325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='descripcion',
            new_name='direccion',
        ),
    ]
