# Generated by Django 3.0.5 on 2020-04-28 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sedes', '0012_auto_20200428_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='productos',
            field=models.ManyToManyField(through='sedes.ProductoVenta', to='sedes.Producto', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
