# Generated by Django 3.0.5 on 2020-04-28 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sedes', '0014_auto_20200428_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='productos',
            field=models.ManyToManyField(blank=True, through='sedes.ProductoVenta', to='sedes.Producto'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='repartidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repartidor', to=settings.AUTH_USER_MODEL),
        ),
    ]
