# Generated by Django 3.0.5 on 2020-04-29 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sedes', '0015_auto_20200428_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodegaProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad de productos en existencia')),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedes.Bodega')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedes.Producto')),
            ],
        ),
        migrations.AddField(
            model_name='bodega',
            name='productos',
            field=models.ManyToManyField(through='sedes.BodegaProducto', to='sedes.Producto'),
        ),
    ]
