# Generated by Django 3.0.5 on 2020-04-29 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sedes', '0016_auto_20200428_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodegaproducto',
            name='cantidad',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad de productos en existencia'),
        ),
        migrations.AlterField(
            model_name='logactualizacioninventario',
            name='cantidad_nueva',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='logactualizacioninventario',
            name='cantidad_vieja',
            field=models.IntegerField(),
        ),
    ]
